In [1]:
import pandas as pd

In [2]:
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [3]:
ser = pd.Series([3,5,7,9])
ser

0    3
1    5
2    7
3    9
dtype: int64

In [4]:
ser.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
ser.values

array([3, 5, 7, 9], dtype=int64)

In [6]:
ser.max()

9

In [8]:
ser.mean()

6.0

In [9]:
ser.idxmax()

3

In [10]:
ser.astype("str") + " value"

0    3 value
1    5 value
2    7 value
3    9 value
dtype: object

In [11]:
ser.to_frame()

0
0  3
1  5
2  7
3  9

In [12]:
ser.reset_index()

index  0
0      0  3
1      1  5
2      2  7
3      3  9

In [13]:
ser.idxmin()

0

In [14]:
"3" + "월"

'3월'

In [15]:
ser.astype("str") + "등"

0    3등
1    5등
2    7등
3    9등
dtype: object

In [17]:
import numpy as np

In [18]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [20]:
np.arange(6).reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [65]:
df = pd.DataFrame(np.arange(6).reshape(3,2),
                 index=["a", "b", "c"],
                 columns=["aa","bb"])

In [66]:
df

aa  bb
a   0   1
b   2   3
c   4   5

In [67]:
df.rename(columns={"aa":"obs"}, inplace=True)
df

obs  bb
a    0   1
b    2   3
c    4   5

In [68]:
df.rename(columns={"bb":"yy"})
df

obs  bb
a    0   1
b    2   3
c    4   5