In [3]:
import pandas as pd
import numpy as np

In [9]:
bike = pd.read_csv("./data/bike.csv")
bike.head(2)

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40

In [12]:
### sampling

In [13]:
bike_sam1= bike.sample(n = 5)
len(bike_sam1)

5

In [14]:
bike_sam2 = bike.sample(frac=0.5)
len(bike_sam2)

5443

In [15]:
np.where(np.array([1,3,5]) >= 3, 1, 0)

array([0, 1, 1])

In [16]:
np.array([1,3,5]) >= 3

array([False,  True,  True])

In [17]:
np.where(np.array([1,3,5]) >= 3, "O", "X")

array(['X', 'O', 'O'], dtype='<U1')

In [18]:
(np.array([1,3,5]) >= 3) + 0

array([0, 1, 1])

In [20]:
bike["season_4"] = ( bike["season"] == 4 ) + 0
bike.head(1)

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   

   humidity  windspeed  casual  registered  count  season_4  
0        81        0.0       3          13     16         0

In [21]:
pd.crosstab(bike["season"], bike["season_4"])

season_4     0     1
season              
1         2686     0
2         2733     0
3         2733     0
4            0  2734

In [22]:
bike_dum = pd.get_dummies(bike, columns=["season"])
bike_dum.head(1)

datetime  holiday  workingday  weather  temp   atemp  humidity  \
0  2011-01-01 00:00:00        0           0        1  9.84  14.395        81   

   windspeed  casual  registered  count  season_4  season_1  season_2  \
0        0.0       3          13     16         0         1         0   

   season_3  season_4  
0         0         0

In [24]:
bike_dum = pd.get_dummies(bike, columns=["season"],
                         drop_first=True)
bike_dum.head(1)

datetime  holiday  workingday  weather  temp   atemp  humidity  \
0  2011-01-01 00:00:00        0           0        1  9.84  14.395        81   

   windspeed  casual  registered  count  season_4  season_2  season_3  \
0        0.0       3          13     16         0         0         0   

   season_4  
0         0